name: Build VIDRA_5 Images

"on":
    workflow_dispatch:

env:
    PREPARE_IMAGE_URI: europe-west1-docker.pkg.dev/open-targets-genetics-dev/opentargets/vidra5-spark-dataproc
    ANNOTATION_IMAGE_URI: europe-west1-docker.pkg.dev/open-targets-genetics-dev/opentargets/vidra5-annotation
    BAYES_IMAGE_URI: europe-west1-docker.pkg.dev/open-targets-genetics-dev/opentargets/vidra5-bayes

jobs:
    build-images:
        name: Build docker images without pushing
        runs-on: ubuntu-22.04

        steps:
            - name: Check out repo
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3.7.0
              with:
                  image: tonistiigi/binfmt:qemu-v7.0.0-28

            - name: Build Step 1 spark image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./docker/spark-dataproc.Dockerfile
                  push: false
                  platforms: linux/amd64
                  tags: |
                      ${{ env.PREPARE_IMAGE_URI }}:latest

            - name: Build annotation image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./docker/annotation.Dockerfile
                  push: false
                  platforms: linux/amd64
                  tags: |
                      ${{ env.ANNOTATION_IMAGE_URI }}:latest

            - name: Build bayes image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./docker/bayes.Dockerfile
                  push: false
                  platforms: linux/amd64
                  tags: |
                      ${{ env.BAYES_IMAGE_URI }}:latest
